.TH zepeto 1 "January 12, 2016"
.SH NAME
zepeto
.SH SYNOPSIS
.B zepeto [options]
.SH DESCRIPTION
.B zepeto
is a tool that allows a user to modify a
shell's environment variables in accordance to defined products.
.SH OPTIONS
.TP
.BI -a " product"
This option attaches the given product. The current shell's environment variables
are modified to reference the paths defined in the zepeto.table file for the given product.
.TP
.BI -d " product"
This option detaches the given product. That is, the environment
variables of the current shell will not reference the paths defined in the
zepeto.table file for the given product.
.TP
.BI -i
Display information about zepeto.
.TP
.BI -l
List all products stored in the official zepeto.table file.
.TP
.BI -t " table"
Use the table table instead of the official zepeto.table table.
.SH FILES
.B
 /usr/local/bin/zepeto.bash
.B
 /usr/local/bin/zepeto.bin
.B
 /usr/local/bin/zepeto.sh
.B
 /usr/local/share/zepeto.table
.SH NOTES
zepeto will issue a warning if a product references a nonexistent path.
You will need to create a zepeto alias for BASH. Please see the
ALIAS EXAMPLE(S) section for more information.
Please note that zepeto will use the /tmp directory if it's unable to locate a user's home directory. Although zepeto uses mkstemp(), the use of /tmp may raise security concerns. Pipelining is supported, however, zepeto temporary files may not be deleted if commands exit prematurely. For example, zepeto -l | sort -1 will result in a dangling zepeto temporary file.
.SH ALIAS EXAMPLE(S)
.IP "bash: alias zepeto='source /usr/local/bin/zepeto.bash'"
.IP "sh: alias zepeto='. /usr/local/bin/zepeto.sh'"
.SH AUTHOR(S)
.B Alexis Megas
